# Generated by Django 4.0.6 on 2022-07-31 14:40

import devicedata.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devicedata', '0002_file_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='deviceprofile',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='content',
            name='order',
            field=devicedata.fields.OrderField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deviceprofile',
            name='order',
            field=devicedata.fields.OrderField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
