# Generated by Django 4.0.6 on 2022-08-06 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devicedata', '0003_alter_content_options_alter_deviceprofile_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='module',
            new_name='deviceprofile',
        ),
    ]
