# Generated by Django 4.0.6 on 2022-07-23 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(max_length=100)),
                ('date_meas', models.DateTimeField()),
                ('time_meas', models.DateTimeField()),
                ('humidity', models.PositiveIntegerField()),
                ('temp_cel', models.PositiveIntegerField()),
                ('temp_fahr', models.PositiveIntegerField()),
                ('class_ISO4', models.PositiveIntegerField()),
                ('class_ISO6', models.PositiveIntegerField()),
                ('class_ISO14', models.PositiveIntegerField()),
                ('class_NAS', models.PositiveIntegerField()),
                ('class_GOST', models.PositiveIntegerField()),
                ('class_SAE4', models.PositiveIntegerField()),
                ('class_SAE6', models.PositiveIntegerField()),
                ('class_SAE14', models.PositiveIntegerField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
