# Generated by Django 4.0.6 on 2022-07-30 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meas_data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measdata',
            name='index',
        ),
        migrations.AlterField(
            model_name='measdata',
            name='class_GOST',
            field=models.IntegerField(verbose_name='GOST'),
        ),
        migrations.AlterField(
            model_name='measdata',
            name='class_ISO14',
            field=models.IntegerField(verbose_name='ISO 14um'),
        ),
        migrations.AlterField(
            model_name='measdata',
            name='class_ISO4',
            field=models.IntegerField(verbose_name='ISO 4um'),
        ),
        migrations.AlterField(
            model_name='measdata',
            name='class_ISO6',
            field=models.IntegerField(verbose_name='ISO 6um'),
        ),
        migrations.AlterField(
            model_name='measdata',
            name='class_NAS',
            field=models.IntegerField(verbose_name='NAS'),
        ),
        migrations.AlterField(
            model_name='measdata',
            name='class_SAE14',
            field=models.IntegerField(verbose_name='SAE 4um'),
        ),
        migrations.AlterField(
            model_name='measdata',
            name='class_SAE4',
            field=models.IntegerField(verbose_name='SAE 4um'),
        ),
        migrations.AlterField(
            model_name='measdata',
            name='class_SAE6',
            field=models.IntegerField(verbose_name='SAE 4um'),
        ),
        migrations.AlterField(
            model_name='measdata',
            name='date_meas',
            field=models.DateField(auto_now=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='measdata',
            name='humidity',
            field=models.IntegerField(verbose_name='humidity'),
        ),
        migrations.AlterField(
            model_name='measdata',
            name='profile',
            field=models.CharField(max_length=100, verbose_name='profile'),
        ),
        migrations.AlterField(
            model_name='measdata',
            name='temp_cel',
            field=models.IntegerField(verbose_name='temperature cel'),
        ),
        migrations.AlterField(
            model_name='measdata',
            name='temp_fahr',
            field=models.IntegerField(verbose_name='temperature fahr'),
        ),
        migrations.AlterField(
            model_name='measdata',
            name='time_meas',
            field=models.TimeField(auto_now=True, verbose_name='time'),
        ),
    ]
