# Generated by Django 4.0.6 on 2022-07-30 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meas_data', '0002_remove_measdata_index_alter_measdata_class_gost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measdata',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
